version: '3.8'

services:
  # PHP & Laravel Application
  app:
    image: php:8.1-fpm
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  # Nginx (web server)
  web:
    image: nginx:alpine
    container_name: nginx-web
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      #MYSQL_ROOT_PASSWORD: yRLGcvXAhuDSbtgBekdrdNuIUTBePUKV
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: yRLGcvXAhuDSbtgBekdrdNuIUTBePUKV
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
